name = "Capes"
filename = "Capes-1.3.0+1.18.2.jar"
side = "client"

[download]
url = "https://cdn.modrinth.com/data/89Wsn8GD/versions/1.3.0+1.18.2/Capes-1.3.0%2B1.18.2.jar"
hash-format = "sha1"
hash = "5a1d6eaeaf9a9bd36f82f720422606784d11f21a"

[update]
[update.modrinth]
mod-id = "89Wsn8GD"
version = "LoKWP6Mn"

[option]
optional = true
default = false
